version: 2.1

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/app
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

workflows:
  version: 2

  build:
    jobs:
      - validate
